SET DATABASE SQL SYNTAX PGS TRUE;
CREATE TYPE BYTEA AS VARBINARY(1000000);
CREATE SEQUENCE tbl_user_user_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tbl_recipe_recipe_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tbl_recipe_photo_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tbl_comment_comment_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tbl_reset_password_token_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tbl_user_verification_token_id_seq START WITH 1 INCREMENT BY 1;
